Attribute VB_Name = "modShapes"
Option Explicit

' ============================================================
'  Picture-Shape renderer (M5a).  Two Shape pools:
'
'   MAZE  - (VIEW_BLOCK + 2)^ grid of block rectangles that
'           follow the smooth camera in points and re-texture
'           only when they scroll onto a different block.
'   ACTOR - rectangles reused each frame for entities / shots /
'           player; the player gets the Elf tile, everything
'           else a flat colour (real monster sprites are M5b).
'
'  Tiles: reference\genesis-tiles\rNN_cNN.png (regenerated by
'  reference\slice-tiles.ps1; Build-Workbook ensures they exist).
' ============================================================

Private Const MZC As Long = VIEW_BLOCK_COLS + 2
Private Const MZR As Long = VIEW_BLOCK_ROWS + 2
Private Const MZN As Long = MZR * MZC
Private Const ACT_POOL As Long = 80

Private mMz() As Shape
Private mMzBR() As Long, mMzBC() As Long          ' world block each maze shape shows now
Private mAct() As Shape
Private mTag() As String                          ' current fill "pic|colour" per shape (1..MZN maze, MZN+1..MZN+ACT_POOL actors)
Private mBlockPts As Double
Private mDir As String
Private mReady As Boolean, mParked As Boolean
Private mLastCamR As Long, mLastCamC As Long

' smoke hook: force a full compile of this module (dead code is still
' reference-checked) without running .Fill.UserPicture, which crashes a
' hidden Excel instance.
Public Sub DebugShapesCompile()
    If True Then Exit Sub
    ShapesFrame 0#
    ParkShapes
    DrawActors
    PutActor 0, 0, 0, 0#, 0, ""
    Fill Nothing, 0, "", 0
End Sub

Public Sub ShapesInit()
    Dim prevSU As Boolean: prevSU = Application.ScreenUpdating
    Application.ScreenUpdating = False

    Dim ws As Worksheet: Set ws = ThisWorkbook.Worksheets(SCREEN_SHEET)
    ws.Activate
    ws.Cells.Interior.Color = CLR_BG
    mDir = ThisWorkbook.Path & "\reference\genesis-tiles\"
    mBlockPts = gCellPts * 2

    Dim s As Shape
    For Each s In ws.Shapes
        If Left$(s.Name, 3) = "mz_" Or Left$(s.Name, 4) = "act_" Then s.Delete
    Next s

    ReDim mMz(1 To MZR * MZC): ReDim mMzBR(1 To MZR * MZC): ReDim mMzBC(1 To MZR * MZC)
    Dim i As Long, r As Long, c As Long
    For r = 0 To MZR - 1
        For c = 0 To MZC - 1
            i = r * MZC + c + 1
            Set mMz(i) = ws.Shapes.AddShape(msoShapeRectangle, c * mBlockPts, r * mBlockPts, mBlockPts, mBlockPts)
            mMz(i).Name = "mz_" & i
            mMz(i).Line.Visible = msoFalse
            mMz(i).Placement = 3
            mMzBR(i) = -30000: mMzBC(i) = -30000
        Next c
    Next r

    ReDim mAct(1 To ACT_POOL)
    For i = 1 To ACT_POOL
        Set mAct(i) = ws.Shapes.AddShape(msoShapeRectangle, -200, -200, mBlockPts, mBlockPts)
        mAct(i).Name = "act_" & i
        mAct(i).Line.Visible = msoFalse
        mAct(i).Placement = 3
        mAct(i).Visible = msoFalse
    Next i

    ReDim mTag(1 To MZN + ACT_POOL)
    mLastCamR = -30000: mLastCamC = -30000
    mReady = True
    Application.ScreenUpdating = prevSU
End Sub

' move the pools off-screen while a menu / result screen is up
Public Sub ParkShapes()
    If Not mReady Or mParked Then Exit Sub
    Dim i As Long
    For i = 1 To MZN: mMz(i).Left = -9000: Next i
    For i = 1 To ACT_POOL: mAct(i).Visible = msoFalse: Next i
    mParked = True
    mLastCamR = -30000: mLastCamC = -30000       ' force a full reposition on resume
End Sub

Public Sub ShapesFrame(ByVal fps As Double)
    If Not mReady Then ShapesInit
    mParked = False

    Dim camBR As Double, camBC As Double
    camBR = (gCamR - 1) / 2#: camBC = (gCamC - 1) / 2#
    Dim topB As Long, leftB As Long
    topB = Int(camBR) - 1: leftB = Int(camBC) - 1

    Dim moved As Boolean: moved = (gCamR <> mLastCamR Or gCamC <> mLastCamC)
    mLastCamR = gCamR: mLastCamC = gCamC

    If moved Then
        Dim i As Long, r As Long, c As Long, wbr As Long, wbc As Long
        For r = 0 To MZR - 1
            For c = 0 To MZC - 1
                i = r * MZC + c + 1
                wbr = topB + r: wbc = leftB + c
                mMz(i).Left = (wbc - camBC) * mBlockPts
                mMz(i).Top = (wbr - camBR) * mBlockPts
                If wbr <> mMzBR(i) Or wbc <> mMzBC(i) Then
                    mMzBR(i) = wbr: mMzBC(i) = wbc
                End If
                Fill mMz(i), i, mDir & MazeTile(wbr, wbc), 0
            Next c
        Next r
    Else
        ' still camera: Fill dedupes, so a cheap sweep catches gen/door changes
        Dim k As Long
        For k = 1 To MZN
            Fill mMz(k), k, mDir & MazeTile(mMzBR(k), mMzBC(k)), 0
        Next k
    End If

    DrawActors
    DrawHud ThisWorkbook.Worksheets(SCREEN_SHEET), fps
End Sub

Private Sub DrawActors()
    Dim n As Long, i As Long
    For i = 1 To gPrjN
        If gPrjKind(i) <> 0 Then n = PutActor(n, gPrjHR(i), gPrjHC(i), 0.5, PrjColour(gPrjKind(i)), "")
    Next i
    For i = 1 To gEntN
        If gEntKind(i) <> K_NONE Then
            If Not (gEntKind(i) = K_SORC) Or SorcVisible(i) Then
                n = PutActor(n, gEntHR(i), gEntHC(i), 1#, EntColour(gEntKind(i)), "")
            End If
        End If
    Next i
    n = PutActor(n, gPlHR, gPlHC, 1#, 0, mDir & TILE_ELF)

    For i = n + 1 To ACT_POOL
        mAct(i).Visible = msoFalse
    Next i
End Sub

' place actor slot n+1 at half-cell (hr,hc); sizeBlk in blocks; pic "" => flat colour
Private Function PutActor(ByVal n As Long, ByVal hr As Long, ByVal hc As Long, _
                          ByVal sizeBlk As Double, ByVal colour As Long, ByVal pic As String) As Long
    If n >= ACT_POOL Then PutActor = n: Exit Function
    n = n + 1
    Dim sp As Shape: Set sp = mAct(n)
    Dim sz As Double: sz = sizeBlk * mBlockPts
    sp.Left = (hc - gCamC) * gCellPts + (mBlockPts - sz) / 2
    sp.Top = (hr - gCamR) * gCellPts + (mBlockPts - sz) / 2
    If Abs(sp.Width - sz) > 0.5 Then sp.Width = sz: sp.Height = sz
    Fill sp, MZN + n, pic, colour
    sp.Visible = msoTrue
    PutActor = n
End Function

' touch .Fill only when the content actually changes (UserPicture is ~0.5ms)
Private Sub Fill(ByVal sp As Shape, ByVal tagIdx As Long, ByVal pic As String, ByVal colour As Long)
    Dim key As String: key = pic & "|" & colour
    If mTag(tagIdx) = key Then Exit Sub
    mTag(tagIdx) = key
    On Error Resume Next
    If pic = "" Then
        sp.Fill.Solid
        sp.Fill.ForeColor.RGB = colour
    Else
        sp.Fill.UserPicture pic
    End If
    On Error GoTo 0
End Sub

Private Function MazeTile(ByVal br As Long, ByVal bc As Long) As String
    If br < 1 Or br > MAP_BLOCK_ROWS Or bc < 1 Or bc > MAP_BLOCK_COLS Then
        MazeTile = TILE_WALL: Exit Function
    End If
    Dim ch As String: ch = gBlock(br, bc)
    If ch = T_WALL Or ch = T_DOOR Then
        MazeTile = TILE_WALL
    ElseIf ch = T_EXIT Then
        MazeTile = TILE_EXIT
    ElseIf IsGen(ch) Then
        MazeTile = TILE_GEN
    Else
        MazeTile = TILE_FLOOR
    End If
End Function

Private Function InMap(ByVal br As Long, ByVal bc As Long) As Boolean
    InMap = (br >= 1 And br <= MAP_BLOCK_ROWS And bc >= 1 And bc <= MAP_BLOCK_COLS)
End Function

Private Function EntColour(ByVal k As Long) As Long
    Select Case k
        Case K_GRUNT:  EntColour = RGB(200, 90, 40)
        Case K_GHOST:  EntColour = RGB(230, 230, 245)
        Case K_DEMON:  EntColour = RGB(170, 40, 40)
        Case K_SORC:   EntColour = RGB(180, 60, 180)
        Case K_LOBBER: EntColour = RGB(60, 170, 70)
        Case K_THIEF:  EntColour = RGB(240, 210, 60)
        Case K_DEATH:  EntColour = RGB(10, 10, 10)
        Case Else:     EntColour = RGB(255, 0, 255)
    End Select
End Function

Private Function PrjColour(ByVal k As Long) As Long
    Select Case k
        Case P_PLAYER: PrjColour = RGB(120, 240, 140)
        Case P_LOBBER: PrjColour = RGB(120, 200, 90)
        Case Else:     PrjColour = RGB(255, 150, 40)
    End Select
End Function
