Attribute VB_Name = "modShapes"
Option Explicit

' ============================================================
'  Picture-Shape renderer (M5a).  Two Shape pools:
'
'   MAZE  - (VIEW_BLOCK + 2)^ grid of block rectangles that
'           follow the smooth camera in points and re-texture
'           only when they scroll onto a different block.
'   ACTOR - rectangles reused each frame for entities / shots /
'           player; the player gets the Elf tile, everything
'           else a flat colour (real monster sprites are M5b).
'
'  Tiles: reference\genesis-tiles\rNN_cNN.png (regenerated by
'  reference\slice-tiles.ps1; Build-Workbook ensures they exist).
' ============================================================

Private Const MZC As Long = VIEW_BLOCK_COLS + 2
Private Const MZR As Long = VIEW_BLOCK_ROWS + 2
Private Const MZN As Long = MZR * MZC
Private Const ACT_POOL As Long = 80

Private mMz() As Shape
Private mMzBR() As Long, mMzBC() As Long          ' world block each maze shape shows now
Private mAct() As Shape
Private mTag() As String                          ' current fill "pic|colour" per shape (1..MZN maze, MZN+1..MZN+ACT_POOL actors)
Private mBlockPts As Double
Private mDir As String
Private mReady As Boolean, mParked As Boolean, mNeedBlank As Boolean
Private mLastCamR As Long, mLastCamC As Long

' smoke hook: force a full compile of this module (dead code is still
' reference-checked) without running .Fill.UserPicture, which crashes a
' hidden Excel instance.
Public Sub DebugShapesCompile()
    If True Then Exit Sub
    Dim s As String, l As Long
    ShapesFrame 0#
    ParkShapes
    DrawActors 0, 0
    MazeCell 0, 0, s, l
    PutActor 0, 0, 0, 0#, 0, ""
    Fill Nothing, 0, "", 0
End Sub

Public Sub ShapesInit()
    Dim prevSU As Boolean: prevSU = Application.ScreenUpdating
    Application.ScreenUpdating = False

    Dim ws As Worksheet: Set ws = ThisWorkbook.Worksheets(SCREEN_SHEET)
    ws.Activate
    ws.Cells.Interior.Color = CLR_BG
    mDir = ThisWorkbook.Path & "\reference\genesis-tiles\"
    mBlockPts = gCellPts * 2

    Dim s As Shape
    For Each s In ws.Shapes
        If Left$(s.Name, 3) = "mz_" Or Left$(s.Name, 4) = "act_" Then s.Delete
    Next s

    ReDim mMz(1 To MZR * MZC): ReDim mMzBR(1 To MZR * MZC): ReDim mMzBC(1 To MZR * MZC)
    Dim i As Long, r As Long, c As Long
    For r = 0 To MZR - 1
        For c = 0 To MZC - 1
            i = r * MZC + c + 1
            Set mMz(i) = ws.Shapes.AddShape(msoShapeRectangle, c * mBlockPts, r * mBlockPts, mBlockPts, mBlockPts)
            mMz(i).Name = "mz_" & i
            mMz(i).Line.Visible = msoFalse
            mMz(i).Placement = 3
            mMzBR(i) = -30000: mMzBC(i) = -30000
        Next c
    Next r

    ReDim mAct(1 To ACT_POOL)
    For i = 1 To ACT_POOL
        Set mAct(i) = ws.Shapes.AddShape(msoShapeRectangle, -200, -200, mBlockPts, mBlockPts)
        mAct(i).Name = "act_" & i
        mAct(i).Line.Visible = msoFalse
        mAct(i).Placement = 3
        mAct(i).Visible = msoFalse
    Next i

    ReDim mTag(1 To MZN + ACT_POOL)
    mLastCamR = -30000: mLastCamC = -30000
    mReady = True
    mNeedBlank = True                 ' clear leftover menu text from the viewport cells
    Application.ScreenUpdating = prevSU
End Sub

' move the pools off-screen while a menu / result screen is up
Public Sub ParkShapes()
    If Not mReady Or mParked Then Exit Sub
    Dim i As Long
    For i = 1 To MZN: mMz(i).Left = -9000: Next i
    For i = 1 To ACT_POOL: mAct(i).Visible = msoFalse: Next i
    mParked = True
    mNeedBlank = True                             ' menu text was just re-written to the cells
    mLastCamR = -30000: mLastCamC = -30000        ' force a full reposition on resume
End Sub

Public Sub ShapesFrame(ByVal fps As Double)
    If Not mReady Then ShapesInit
    Dim prevSU As Boolean: prevSU = Application.ScreenUpdating
    Application.ScreenUpdating = False          ' batch all shape ops into one repaint

    If mNeedBlank Then BlankPlayfield: mNeedBlank = False   ' kill menu text under the part-transparent tiles
    mParked = False

    ' camera top-left in fractional BLOCK units. gCam* is the half-cell at the
    ' viewport edge (1-based); block bc's left edge is half-cell 2*bc-1, so the
    ' block-space camera is (gCam + 1) / 2 to match the actor coordinate system.
    Dim camBR As Double, camBC As Double
    camBR = (gCamR + 1) / 2#: camBC = (gCamC + 1) / 2#
    Dim topB As Long, leftB As Long
    topB = Int(camBR) - 1: leftB = Int(camBC) - 1

    Dim moved As Boolean: moved = (gCamR <> mLastCamR Or gCamC <> mLastCamC)
    mLastCamR = gCamR: mLastCamC = gCamC

    Dim pc As String, cl As Long
    If moved Then
        Dim i As Long, r As Long, c As Long, wbr As Long, wbc As Long
        For r = 0 To MZR - 1
            For c = 0 To MZC - 1
                i = r * MZC + c + 1
                wbr = topB + r: wbc = leftB + c
                mMz(i).Left = (wbc - camBC) * mBlockPts
                mMz(i).Top = (wbr - camBR) * mBlockPts
                mMzBR(i) = wbr: mMzBC(i) = wbc
                MazeCell wbr, wbc, pc, cl
                Fill mMz(i), i, pc, cl
            Next c
        Next r
    ElseIf gBlocksChanged Then
        Dim k As Long
        For k = 1 To MZN
            MazeCell mMzBR(k), mMzBC(k), pc, cl
            Fill mMz(k), k, pc, cl
        Next k
    End If
    gBlocksChanged = False

    DrawActors topB, leftB
    DrawHud ThisWorkbook.Worksheets(SCREEN_SHEET), fps
    Application.ScreenUpdating = prevSU
End Sub

Private Sub BlankPlayfield()
    Dim ws As Worksheet: Set ws = ThisWorkbook.Worksheets(SCREEN_SHEET)
    ws.Range(ws.Cells(1, 1), ws.Cells(VIEW_ROWS, VIEW_COLS)).ClearContents
End Sub

Private Sub DrawActors(ByVal topB As Long, ByVal leftB As Long)
    Dim n As Long, i As Long, br As Long, bc As Long
    Dim frame As Long: frame = (timeGetTime() \ ANIM_MS) Mod 3

    ' floor items
    For br = topB To topB + MZR
        For bc = leftB To leftB + MZC
            If InMap(br, bc) Then
                Select Case gBlock(br, bc)
                    Case T_KEY:    n = PutActor(n, br * 2 - 1, bc * 2 - 1, 0.7, 0, SprFile(SPR_ITEM_KEY))
                    Case T_FOOD:   n = PutActor(n, br * 2 - 1, bc * 2 - 1, 0.8, 0, SprFile(SPR_ITEM_MEAT))
                    Case T_POTION: n = PutActor(n, br * 2 - 1, bc * 2 - 1, 0.8, 0, SprFile(SPR_ITEM_POT))
                End Select
            End If
        Next bc
    Next br

    ' projectiles
    For i = 1 To gPrjN
        If gPrjKind(i) <> 0 Then
            Dim pspr As Long
            pspr = IIf(gPrjKind(i) = P_PLAYER, SPR_ARROW, SPR_FIREBALL) + DirIndex(gPrjDR(i), gPrjDC(i))
            n = PutActor(n, gPrjHR(i), gPrjHC(i), 0.8, PrjColour(gPrjKind(i)), SprFile(pspr))
        End If
    Next i

    ' monsters - per-kind sprite block + frame*8 + facing
    For i = 1 To gEntN
        If gEntKind(i) <> K_NONE Then
            If Not (gEntKind(i) = K_SORC) Or SorcVisible(i) Then
                Dim mb As Long: mb = MonBase(gEntKind(i))
                n = PutActor(n, gEntHR(i), gEntHC(i), 1#, EntColour(gEntKind(i)), _
                             SprFile(mb + frame * 8 + gEntDir(i)))
            End If
        End If
    Next i

    ' player - chosen hero, walk frame (mid-stride when idle) + facing
    Dim pf As Long
    pf = IIf(gInUp Or gInDown Or gInLeft Or gInRight, frame, 1)
    n = PutActor(n, gPlHR, gPlHC, 1#, 0, _
                 SprFile(SPR_HERO_BASE + gChar * SPR_HERO_STRIDE + pf * 8 + DirIndex(gFaceDR, gFaceDC)))

    For i = n + 1 To ACT_POOL
        mAct(i).Visible = msoFalse
    Next i
End Sub

Private Function MonBase(ByVal k As Long) As Long
    Select Case k
        Case K_GHOST:  MonBase = SPR_GHOST
        Case K_GRUNT:  MonBase = SPR_GRUNT
        Case K_DEMON:  MonBase = SPR_IMP
        Case K_SORC:   MonBase = SPR_BADWIZ
        Case K_LOBBER: MonBase = SPR_BLOB
        Case K_THIEF:  MonBase = SPR_HEAD
        Case K_DEATH:  MonBase = SPR_DEATH
        Case Else:     MonBase = SPR_GRUNT
    End Select
End Function

' stream index -> tile path ("" if the tile wasn't sliced). Cached: the Dir$
' check and the string build happen once per index for the session.
Private mSprCache() As String

Private Function SprFile(ByVal idx As Long) As String
    If idx < 0 Or idx > 703 Then Exit Function
    If (Not Not mSprCache) = 0 Then
        ReDim mSprCache(0 To 703)
        Dim j As Long
        For j = 0 To 703: mSprCache(j) = vbNullChar: Next j    ' sentinel = not yet checked
    End If
    If mSprCache(idx) = vbNullChar Then
        Dim p As String
        p = mDir & "r" & Format$(idx \ 44, "00") & "_c" & Format$(idx Mod 44, "00") & ".png"
        mSprCache(idx) = IIf(Dir$(p) <> "", p, "")
    End If
    SprFile = mSprCache(idx)
End Function

' place actor slot n+1 at half-cell (hr,hc); sizeBlk in blocks; pic "" => flat colour
Private Function PutActor(ByVal n As Long, ByVal hr As Long, ByVal hc As Long, _
                          ByVal sizeBlk As Double, ByVal colour As Long, ByVal pic As String) As Long
    If n >= ACT_POOL Then PutActor = n: Exit Function
    n = n + 1
    Dim sp As Shape: Set sp = mAct(n)
    Dim sz As Double: sz = sizeBlk * mBlockPts
    sp.Left = (hc - gCamC) * gCellPts + (mBlockPts - sz) / 2
    sp.Top = (hr - gCamR) * gCellPts + (mBlockPts - sz) / 2
    If Abs(sp.Width - sz) > 0.5 Then sp.Width = sz: sp.Height = sz
    Fill sp, MZN + n, pic, colour
    sp.Visible = msoTrue
    PutActor = n
End Function

' touch .Fill only when the content actually changes (UserPicture is ~0.5ms)
Private Sub Fill(ByVal sp As Shape, ByVal tagIdx As Long, ByVal pic As String, ByVal colour As Long)
    Dim key As String: key = pic & "|" & colour
    If mTag(tagIdx) = key Then Exit Sub
    mTag(tagIdx) = key
    On Error Resume Next
    If pic = "" Then
        sp.Fill.Solid
        sp.Fill.ForeColor.RGB = colour
    Else
        sp.Fill.UserPicture pic
    End If
    On Error GoTo 0
End Sub

' terrain fill for a block: a tile path, or (pic="") a flat colour
Private Sub MazeCell(ByVal br As Long, ByVal bc As Long, ByRef pic As String, ByRef colour As Long)
    pic = "": colour = 0
    If br < 1 Or br > MAP_BLOCK_ROWS Or bc < 1 Or bc > MAP_BLOCK_COLS Then
        pic = mDir & TILE_WALL: Exit Sub                 ' void beyond the map
    End If
    Dim ch As String: ch = gBlock(br, bc)
    Select Case ch
        Case T_WALL:  pic = mDir & TILE_WALL
        Case T_EXIT:  pic = mDir & TILE_EXIT
        Case T_DOOR:  colour = RGB(140, 85, 45)          ' solid brown - readable vs the blue wall
        Case Else
            If IsGen(ch) Then
                pic = SprFile(SPR_GENERATOR)
                If pic = "" Then colour = RGB(150, 40, 40)
            Else
                pic = mDir & TILE_FLOOR
            End If
    End Select
End Sub

Private Function InMap(ByVal br As Long, ByVal bc As Long) As Boolean
    InMap = (br >= 1 And br <= MAP_BLOCK_ROWS And bc >= 1 And bc <= MAP_BLOCK_COLS)
End Function

Private Function EntColour(ByVal k As Long) As Long
    Select Case k
        Case K_GRUNT:  EntColour = RGB(200, 90, 40)
        Case K_GHOST:  EntColour = RGB(230, 230, 245)
        Case K_DEMON:  EntColour = RGB(170, 40, 40)
        Case K_SORC:   EntColour = RGB(180, 60, 180)
        Case K_LOBBER: EntColour = RGB(60, 170, 70)
        Case K_THIEF:  EntColour = RGB(240, 210, 60)
        Case K_DEATH:  EntColour = RGB(10, 10, 10)
        Case Else:     EntColour = RGB(255, 0, 255)
    End Select
End Function

Private Function PrjColour(ByVal k As Long) As Long
    Select Case k
        Case P_PLAYER: PrjColour = RGB(120, 240, 140)
        Case P_LOBBER: PrjColour = RGB(120, 200, 90)
        Case Else:     PrjColour = RGB(255, 150, 40)
    End Select
End Function
